-- =============================================================================
--  Sales Order module.
--
--  Purely additive: one new table and two new enums. No existing table, column,
--  index or constraint is altered, so applying this cannot affect Product
--  Enquiry, the Customer master or anything already in the database.
--
--  The six CHECK constraints at the end are hand-written, following the same
--  pattern as 20260825090309_business_invariants. They are what turn the money
--  and lifecycle rules from application conventions into database guarantees.
-- =============================================================================

-- CreateEnum
CREATE TYPE "SalesOrderStatus" AS ENUM ('OPEN', 'DISPATCHED', 'CLOSED');

-- CreateEnum
CREATE TYPE "SalesEfficiency" AS ENUM ('ON_TIME', 'DELAYED');

-- CreateTable
CREATE TABLE "SalesOrder" (
    "id" TEXT NOT NULL,
    "orderId" TEXT NOT NULL,
    "customerId" TEXT NOT NULL,
    "productName" TEXT NOT NULL,
    "productImageId" TEXT,
    "quantity" INTEGER NOT NULL,
    "price" DECIMAL(12,2) NOT NULL,
    "paidAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "orderDate" TIMESTAMP(3) NOT NULL,
    "toBeDispatchedBy" TIMESTAMP(3) NOT NULL,
    "status" "SalesOrderStatus" NOT NULL DEFAULT 'OPEN',
    "dispatchedAt" TIMESTAMP(3),
    "efficiency" "SalesEfficiency",
    "closedAt" TIMESTAMP(3),
    "closedById" TEXT,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SalesOrder_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "SalesOrder_orderId_key" ON "SalesOrder"("orderId");

-- CreateIndex
CREATE INDEX "SalesOrder_status_toBeDispatchedBy_idx" ON "SalesOrder"("status", "toBeDispatchedBy");

-- CreateIndex
CREATE INDEX "SalesOrder_customerId_idx" ON "SalesOrder"("customerId");

-- CreateIndex
CREATE INDEX "SalesOrder_orderDate_idx" ON "SalesOrder"("orderDate");

-- CreateIndex
CREATE INDEX "SalesOrder_efficiency_orderDate_idx" ON "SalesOrder"("efficiency", "orderDate");

-- AddForeignKey
ALTER TABLE "SalesOrder" ADD CONSTRAINT "SalesOrder_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SalesOrder" ADD CONSTRAINT "SalesOrder_productImageId_fkey" FOREIGN KEY ("productImageId") REFERENCES "MediaAsset"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SalesOrder" ADD CONSTRAINT "SalesOrder_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SalesOrder" ADD CONSTRAINT "SalesOrder_closedById_fkey" FOREIGN KEY ("closedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- -----------------------------------------------------------------------------
--  Business invariants — hand-written, not generated by Prisma.
-- -----------------------------------------------------------------------------

-- Quantity is manually entered, whole numbers only, minimum 1.
ALTER TABLE "SalesOrder"
  ADD CONSTRAINT "sales_quantity_positive"
    CHECK ("quantity" > 0);

-- Price is manually entered and must be positive. A zero-price order is a
-- data-entry mistake, not a free gift.
ALTER TABLE "SalesOrder"
  ADD CONSTRAINT "sales_price_positive"
    CHECK ("price" > 0);

-- Partial payments are allowed, but never more than the order is worth.
--
-- The ceiling is written against "quantity" * "price" rather than a stored
-- total column, so the database and the API share one definition of the total
-- instead of two that can drift apart.
ALTER TABLE "SalesOrder"
  ADD CONSTRAINT "sales_paid_within_total"
    CHECK ("paidAmount" >= 0 AND "paidAmount" <= "quantity" * "price");

-- The dispatch deadline cannot fall before the order was placed. Same-day is
-- legitimate, which is why this is >= and not >.
ALTER TABLE "SalesOrder"
  ADD CONSTRAINT "sales_dispatch_not_before_order"
    CHECK ("toBeDispatchedBy" >= "orderDate");

-- The dispatch moment and its verdict are written together or not at all, so a
-- dispatched order can never be missing its efficiency and an undispatched one
-- can never have acquired a verdict.
ALTER TABLE "SalesOrder"
  ADD CONSTRAINT "sales_efficiency_accompanies_dispatch"
    CHECK (("dispatchedAt" IS NULL) = ("efficiency" IS NULL));

-- A closed order always records when it closed and who closed it.
ALTER TABLE "SalesOrder"
  ADD CONSTRAINT "sales_closed_has_closer"
    CHECK ("status" <> 'CLOSED'
           OR ("closedAt" IS NOT NULL AND "closedById" IS NOT NULL));
